### PR TITLE
Log TCP health checks at debug level

### LINKED ISSUE #36: Don't log connection error for tcp health check
The error log is filled with "MQTT detected network error" because of the load balancers health checks. Could you (as it has been done for the amqp plugin) prevent error logging when no data is sent between  connection and disconnection (see : https://groups.google.com/forum/#!topic/rabbitmq-users/h1wGglkVvZQ)

### PR DESCRIPTION
**Pull request by hairyhum**
Fixes #36

### CODE REVIEW

**Comment by michaelklishin** [comment]
Assigning to @dumbbell because he did the same thing for at least one other protocol (AMQP 0-9-1).

**Comment by michaelklishin** [comment]
@hairyhum this changes log entry format. The scope of #36 is only to not log anything when there was no data sent on a connection. We did this for AMQP 0-9-1 some time in the last year.

**Comment by michaelklishin** [comment]
The original server change is https://github.com/rabbitmq/rabbitmq-server/commit/3231071cdc84c1a62e29a0b214be78a805f14de2, which actually does the same thing. OK then, lets use this format across the board.

**Comment by michaelklishin** [comment]
With this, we log https://gist.github.com/michaelklishin/25b8a858013d03896706 for "real" connections
and nothing for telnet connections that C-] and quit immediately. This is what we want.

However, note that INFO REPORT log entries use local time but "accepted at …" is in UTC.

For AMQP 0-9-1, it is

```
=INFO REPORT==== 8-Jan-2016::15:51:37 ===
accepting AMQP connection <0.1102.0> (127.0.0.1:54483 -> 127.0.0.1:5672)
```

and has no double time stamping.

**Comment by hairyhum** [comment]
Maybe there should be some other format for protocol connection log?

**Comment by michaelklishin** [comment]
The one we have in `rabbitmq-server` works pretty well. We don't hear complaints about those entries for legitimate connections (as in, non-health checks).

**Comment by michaelklishin** [comment]
OK, it works as expected now.

**Comment by michaelklishin** [comment]
Rebased to `stable`, will be in `3.6.1`.

**Pull request merged**
