### PR TITLE
Refactor java tests

### PR DESCRIPTION
**Pull request by lukebakken**
The current test suite has some shared state between tests that has been problematic. This work will attempt to simplify the necessary topic permissions as well.

### CODE REVIEW

**Comment by michaelklishin** [comment]
@lukebakken anything else left to do in this PR?

**Comment by lukebakken** [comment]
Yep, still working on it!

**Comment by lukebakken** [comment]
@michaelklishin all set. I don't think I can remove any more topics that are being used.

**Comment by lukebakken** [comment]
@michaelklishin thanks for backporting to `v3.8.x` and `v3.7.x`

**Pull request merged**
