### PR TITLE
If CleanSession is false, QoS0 Topic should remain.

### PR DESCRIPTION
**Pull request by HyeongseokLim**
Hi~

The QoS0 topic can not remember because it always deleted. 

So i remain QoS0 queue, add x-message-ttl to 0.

Please check it.

### CODE REVIEW

**Comment by michaelklishin** [comment]
TTL 0 means "delete immediately". What's the point?

**Comment by HyeongseokLim** [comment]
The Session state in the Server consists of: The Client’s subscriptions.

mosquito memory QoS0 and QoS1 Topics.
But rabbitmq-mqtt memory only QoS1 Topics.

TTL 0 means 'QoS0 Queue'. It is published when the consumer exists.

**Comment by michaelklishin** [comment]
I understand the intent to make the `Clean Session` flag control whether or not a queue is declared as auto-delete. I definitely do not understand what's the point of having message TTL set to 0 even in that case. You effectively discard all messages when there are no consumers but keep the queue around. 

Currently when the last consumer leaves the entire queue will be deleted: how is it really different to clients? Why have a queue at all if without consumers it won't accumulate any messages anyway?

**Comment by michaelklishin** [comment]
The proposed change makes no practical sense.

We can do one of two things:

 * Make the clean session flag on `QoS 0` subscriptions control whether or not its queue is auto-deleted *and* set a `x-expires` on it, just like with `QoS 1` queue, so that we do not accumulate queues forever when its subscriber is gone.
 * Leave things as is.

We haven't heard any complains about the current behaviour since #30 and #37, which both make sense because they are about `QoS 1` subscriber queues. Unless someone comes up with a compelling reason to worry about this for `QoS 0`, I'd just leave things the way they are.

**Comment by michaelklishin** [comment]
@michaelplaing does my reasoning above make sense to you?

**Comment by HyeongseokLim** [comment]
We have used the mosquito. Now, we changed to use the rabbitmq-mqtt for high availability, scalability. Our clients have some problem about QoS0 Topics are missing. So, i had to fix it. 

QoS0 Queue will set a x-expires by subscription_ttl, just like with QoS1 queue.

**Comment by michaelklishin** [comment]
"some problems about QoS0 Topics missing" is not very specific. `rabbitmq-mqtt` will ensure queues exist whenever you add a subscriber.

I'm closing this as it is no different than what we have today as far as clients go and the complexity is higher. If you can provide more information about the difference, please post them to rabbitmq-users.

**Pull request closed without merging**
