### PR TITLE
Propagate client ID to authn with dedicated module

### LINKED ISSUE #139: Investigate if client ID can be safely propagated to authn backends
See https://github.com/rabbitmq/rabbitmq-mqtt/pull/137 for the idea. This makes sense for some authn backends (e.g. HTTP, possibly LDAP) but not others (e.g. internal database backend won't use the client ID value).

[rabbit_authn_backend: user_login_authentication/2](https://github.com/rabbitmq/rabbitmq-common/blob/master/src/rabbit_authn_backend.erl) already accepts additional options.

@acogoluegnes may have additional thoughts.

### PR DESCRIPTION
**Pull request by acogoluegnes**
Fixes #139

### CODE REVIEW

**Comment by michaelklishin** [comment]
I'm getting multiple test failures after updating this to master which currently had a lot of files moved around between rabbitmq-server, amqp_client and rabbitmq-common.

**Comment by michaelklishin** [comment]
Here are CT logs that demonstrate the failures: [rabbitmq_mqtt_139_ct_logs.zip](https://github.com/rabbitmq/rabbitmq-mqtt/files/1103380/rabbitmq_mqtt_139_ct_logs.zip).

**Comment by michaelklishin** [comment]
I confirm that after an umbrella-wide `gmake distclean`, the tests pass in master.

**Comment by acogoluegnes** [comment]
OK, I reproduced the tests failures on the branch. I merged the branch with master and the tests pass.

**Pull request merged**
