### PR TITLE
Retained messages support

### LINKED ISSUE #16: Support retain flag
We've seen enough requests for `RETAIN` to be supported.

A high profile user N wants to store retained messages in Cassandra. It makes sense to make the initial implementation to store messages in RAM (possibly with a TTL).

### PR DESCRIPTION
**Pull request by michaelklishin**
Fixes #16.

### CODE REVIEW

**Comment by Hades32** [comment]
Is there already some documentation? Especially on what the limits of the implementation are?

**Comment by michaelklishin** [comment]
@Hades32 see [next.rabbitmq.com](http://next.rabbitmq.com/mqtt.html).

**Comment by smurfix** [comment]
@michaelklishin ?? http://next.rabbitmq.com/mqtt.html does not mention RETAIN, nor any message store.

**Comment by michaelklishin** [comment]
Yes, it does. I re-deployed `next` docs just in case.

**Pull request merged**
